name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' # Specify the Node.js version

      - name: Install dependencies for strava-api-lib
        working-directory: strava-api-lib
        run: |
          npm install
          npm run build

      - name: Run tests for strava-api-lib
        working-directory: strava-api-lib
        run: npm test

      - name: Install dependencies for strava-test-app
        working-directory: strava-test-app
        run: npm install

      - name: Run tests for strava-test-app
        working-directory: strava-test-app
        run: npm test